baseurl = "https://climbing40.ru"
enablerobotstxt = true
paginate = 50
timezone = "Europe/Moscow"
titlecasestyle = "Go"

defaultContentLanguage = 'ru'
[languages]
[languages.en]
disable = true
[languages.ru]
languageCode = 'ru-RU'
languageDirection = 'ltr'
languageName = 'Russian'
weight = 1

[params.paige]
color = "#0d6efd"
color_scheme = "light"
date_format = ":date_long"
title = "Федерация скалолазания Калужской области"
description = "Скалолазание в Калуге и области"
external_link_new_tab = true
keyword_style = "pills"                            # Must be "text" or "pills"
math = false
menu_style = "underline"                           # Must be "links", "pills", "tabs", or "underline"
copyright = "2025 © РОО ФСКО"

[params.paige.analytics]
disable = true # Disable all analytics

[params.paige.site]
disable_breadcrumbs = true

[params.paige.page]
disable_alert = true
disable_authors = true
disable_date = true
disable_description = true
disable_edit = true
disable_history = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
# disable_title = true
disable_toc = true

[params.paige.list_page]
# disable_authors = true
# disable_collections = true
# disable_date = true
# disable_description = true
# disable_keywords = true
# disable_pages = true
# disable_reading_time = true
disable_sections = true
# disable_series = true
# disable_summary = true
# disable_title = true


[[languages.ru.menu.main]]
identifier = "home"
name = "Главная"
url = "/"
weight = 10

[[languages.ru.menu.main]]
identifier = "gyms"
name = "Скалодромы"
url = "/gyms/"
weight = 20

[[languages.ru.menu.main]]
identifier = "climbing"
name = "О скалолазании"
url = "/climbing/"
weight = 30

[[languages.ru.menu.main]]
identifier = "news"
name = "Новости"
url = "/news/"
weight = 31

[[languages.ru.menu.main]]
identifier = "calendar"
name = "Календарь"
url = "/calendar/"
weight = 40

[[languages.ru.menu.main]]
identifier = "contacts"
name = "Контакты"
url = "/contacts/"
weight = 50

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[taxonomies]
# author = "authors"
# category = "categories"
# series = "series"
tag = "tags"
