baseurl = "https://climbing40.ru"
enablerobotstxt = true
languagecode = "ru-ru"
paginate = 50
timezone = "Europe/Moscow"
titlecasestyle = "Go"

[params.paige]
color = "#0d6efd" 
color_scheme = "light" 
date_format = ":date_long"
title = "Федерация скалолазания Калужской области"
description = "Скалолазание в Калуге и области"
external_link_new_tab = true 
keyword_style = "pills" # Must be "text" or "pills"
math = false 
menu_style = "underline" # Must be "links", "pills", "tabs", or "underline"
copyright = "2025 © РОО ФСКО"

[params.paige.analytics]
disable = true # Disable all analytics

[params.paige.site]
disable_breadcrumbs = true

[params.paige.page]
disable_alert = false
disable_authors = false
disable_date = false
disable_description = false
disable_edit = false
disable_history = false
disable_keywords = false
disable_next = true
disable_prev = true
disable_reading_time = false
disable_series = false
disable_title = false
disable_toc = false

[[languages.en.menu.main]]
identifier = "home"
name = "Главная"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "gyms"
name = "Скалодромы"
url = "/gyms/"
weight = 20

[[languages.en.menu.main]]
identifier = "climbing"
name = "О скалолазании"
url = "/climbing/"
weight = 30

[[languages.en.menu.main]]
identifier = "news"
name = "Новости"
url = "/news/"
weight = 31

[[languages.en.menu.main]]
identifier = "calendar"
name = "Календарь"
url = "/calendar/"
weight = 40

[[languages.en.menu.main]]
identifier = "contact"
name = "Контакты"
url = "/contact/"
weight = 50

[markup.goldmark.parser.attribute]
    block = true
    title = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[taxonomies]
# author = "authors"
# category = "categories"
# series = "series"
tag = "tags"
